apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    purpose: service-np-demo

spec:
  type: NodePort
  selector:
    purpose: service-np-demo
    project: roboshop
    environment: dev

  ports:
    - protocol: TCP
      port: 80        # Service Port
      targetPort: 80  # Container Port

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: service-np-demo
    project: roboshop
    environment: dev

spec:
  containers:
    - name: nginx
      image: nginx



